#!/usr/bin/env dash

dbus-monitor "type='signal',sender='org.freedesktop.DBus',member='NameAcquired'" |
while read -r line; do
    [ "$(echo "$line" | grep -E "^signal")" ] &&\
        play-notification-sound &
done
