#!/usr/bin/env dash

LOCK_FILE="$XDG_RUNTIME_DIR/notif-sound.lock"

BASE_DIR=$(dirname $(readlink "$0" || echo "$0"))

! [  -f "$LOCK_FILE" ] &&\
    trap "rm -f $LOCK_FILE; exit" INT EXIT &&\
    touch "$LOCK_FILE" &&\
    mpv --really-quiet --no-video --keep-open=no --end=00:02 --volume=50 "$BASE_DIR/assets/notification.ogg"

exit 0
