#!/usr/bin/env dash

killall -e -q xdg-desktop-portal-gtk
killall -e -q xdg-desktop-portal-hyprland
killall -e -q xdg-desktop-portal

ENV_VARS="WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GTK_THEME QT_QPA_PLATFORMTHEME XCURSOR_SIZE XCURSOR_THEME "\
    "WLR_DRM_NO_ATOMIC XDG_SESSION_DESKTOP XDG_SESSION_TYPE HYPRCURSOR_THEME HYPRCURSOR_SIZE GTK_USE_PORTAL"

# Gnome settings
gsettings set org.gnome.desktop.interface cursor-theme 'material_light_cursors'

# Slow app launch fix
#export $(dbus-launch)
dbus-update-activation-environment --systemd --all
echo $ENV_VARS | xargs systemctl --user import-environment

systemctl --user start xdg-desktop-portal
systemctl --user start xdg-desktop-portal-hyprland &
systemctl --user start xdg-desktop-portal-gtk &

sleep 3

echo "$HYPRLAND_INSTANCE_SIGNATURE" > "$HYPR_SIG_FILE"
# udiskie &
start-wallpaper &
# blueman-tray &
# nm-applet --indicator &
# motrix --enable-features=UseOzonePlatform --ozone-platform=wayland &
# start-playerctl &
# start-kdeconnect &
# start-devicebattery &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# protonmail-bridge --no-window &
# xwayland-config &
# start-update-check &
start-statusbar &
# start-notifications &
#start-idle &
#hyprpm reload -n &
