#!/bin/bash

PPWIRE_TYPE="PipeWire:Interface:Node"
SINK_MEDIA_CLASS="Audio/Sink"

SINKS=$(pw-dump | jq -r \
    --arg PPWIRE_TYPE "$PPWIRE_TYPE" \
    --arg SINK_MEDIA_CLASS "$SINK_MEDIA_CLASS" \
    --arg PROP_MC_NAME "media.class"\
    --arg PROP_NODE_DESC "node.description"\
    '[.[] | select(.type == $PPWIRE_TYPE and .info.props[$PROP_MC_NAME] == $SINK_MEDIA_CLASS)] | map({"id": .id, "description": .info.props[$PROP_NODE_DESC]})')

SELECTED=$(echo "$SINKS" | jq -r '.[] | .description' | rofi -dmenu -p "Audio Device:")

[[ ! -z "$SELECTED" ]] &&\
    wpctl set-default $(echo "$SINKS" | jq --arg DESC "$SELECTED" -r '.[] | select(.description == $DESC) | .id')
