#!/usr/bin/env sh

REPO="https://api.github.com/repos/google/google-java-format/releases/latest"
TEMP=$(mktemp)
trap "rm -f $TEMP" INT EXIT

curl -s "$REPO" -o "$TEMP"

VERSION=$(cat "$TEMP" | jq -r '.name')

[ -z "$XDG_DATA_HOME" ] &&\
    NVIM_DATA_BASE="$HOME/.local/share/nvim" || NVIM_DATA_BASE="$XDG_DATA_HOME/nvim"

TARGET_FOLDER="$NVIM_DATA_BASE/google-java-format"
TARGET_FILE="$TARGET_FOLDER/google-java-format.jar"
VERSION_FILE="$TARGET_FOLDER/version.txt"

mkdir -p "$TARGET_FOLDER"

if [ -f "$VERSION_FILE" ]; then
    CURRENT_VERSION=$(cat "$VERSION_FILE")
fi

if ! [ "$VERSION" = "$CURRENT_VERSION" ]; then
    URL=$(cat "$TEMP" | jq -r '.assets[] | select(.name | contains("all-deps.jar")) | .browser_download_url')
    curl -sL "$URL" -o "$TARGET_FILE"
    echo "$VERSION" > "$VERSION_FILE"
fi

