#!/usr/bin/env sh

PROMPT="Kill: "
PIDS=$(run-launcher --pid)

[ -n "$PIDS" ] && kill -9 $PIDS && exit

ENTRIES=""

TEMP=$(mktemp)
trap "rm -f $TEMP" INT EXIT
ps -o pid,cmd -u "$USER" | tail -n +2 > "$TEMP"

while read proc; do
    PS_PID=$(echo "$proc" | cut -d ' ' -f1) 
    PS_CMD=$(echo "$proc" | cut -d ' ' -f2-) 

    ENTRIES="$ENTRIES$PS_PID | $(echo "$PS_CMD" | awk '{print substr($0,0,20)" ... "substr($0,length($0)-29,30)}')\n"
done < "$TEMP"

TARGET=$(echo "$ENTRIES" | run-launcher "$PROMPT")

if [ -n "$TARGET" ]; then
    kill -9 $(echo "$TARGET" | cut -d ' ' -f1)
fi

