#!/bin/bash

pkill -9 wineboot.exe

[[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]] \
    && source $(which set-hyprland-socket) \
    && hyprctl --batch "dispatch workspace 1 ; dispatch togglespecialworkspace steam"

