#!/usr/bin/env sh

[ $(which xwayland-config) ] && xwayland-config

BIN=$([ $(which steam-native) ] && echo "steam-native" || echo "steam-runtime")
EXTRA_ARGS=$(echo "$@" | tr ' ' '\n')

echo "$EXTRA_ARGS" | xargs "$BIN"
