#!/bin/bash

WS="$1"
PROC="$1"
BIN=""

proc_bin_override() {
    case "$1" in
#        steam) BIN="mangohud steam-native";;
        btwarden) BIN="com.bitwarden.desktop"; PROC="bitwarden";;
        *) BIN="$1";;
    esac
}

proc_bin_override "$WS"

if [[ -z $(pgrep "$PROC") ]]; then
    $BIN &
    exit
fi

source $(which set-hyprland-socket)
exec hyprctl dispatch togglespecialworkspace "$WS"
