#!/bin/bash

APP_ID_REGEX="AppId=([0-9]+)"
[[ $(echo "$@") =~ $APP_ID_REGEX ]] &&\
    export STEAM_APPID="${BASH_REMATCH[1]}"

GENERAL_TWEAKS="general-tweaks"
EOS_TWEAKS="eos-ovl-tweaks"
GAMEMODE_COMMAND="gamemoderun"

source $(which $GENERAL_TWEAKS)

exec\
    $EOS_TWEAKS\
    $GAMEMODE_COMMAND\
	"$@"
