#!/bin/bash

if [[ -z "$1" ]]; then
    "$EDITOR" .
    exit
fi

OLD_PWD=$(pwd)

trap "cd ${OLD_PWD}; exit" SIGINT ERR EXIT

if [[ -d "$1" ]]; then 
    cd "$1" 
    "$EDITOR" .
    exit
fi

cd $(dirname "$1")
"$EDITOR" "$1"
