#!/usr/bin/env sh

if [ -z "$1" ] || [ "$1" = "." ]; then
    SESSION=$(basename $(pwd))
    tmux new -A -c $(pwd) -d -s "$SESSION" "$EDITOR" .
    tmux switch-client -t "$SESSION" 
    exit
fi

OLD_PWD=$(pwd)

trap "cd ${OLD_PWD}; exit" INT EXIT

if [ -d "$1" ]; then 
    SESSION=$(basename "$1")
    tmux new -A -c "$1" -d -s "$SESSION" "$EDITOR" .
    tmux switch-client -t "$SESSION" 
    exit
fi

REALPATH=$(readlink -f "$1")

TARGET_DIR="$(dirname "$REALPATH")"

SESSION="$(basename $TARGET_DIR)"
tmux new-session -A -c "$TARGET_DIR" -d -s "$SESSION" "$EDITOR" "$REALPATH"
tmux switch-client -t "$SESSION" 
