#!/bin/bash

BIN=$([[ $(which brave-beta 2>/dev/null) ]] && echo "brave-beta" || echo "brave")
EXTRA_ARGS=$(echo "$@" | tr ' ' '\n')

(echo "$EXTRA_ARGS" && cat $HOME/.config/chromium-flags.conf) | xargs "$BIN"
