#!/usr/bin/env dash

WS="$1"
PROC="$1"
BIN=""

proc_bin_override() {
    case "$1" in
        steam) BIN="steam-native";;
        btwarden) BIN="bitwarden-desktop"; PROC="app.asar";;
        *) BIN="$1";;
    esac
}

proc_bin_override "$WS"

if [ -z $(pidof "$PROC") ]; then
    $BIN &
    exit
fi

source $(which set-hyprland-socket)
exec hyprctl dispatch togglespecialworkspace "$WS"
