#!/usr/bin/env bash

SEARCH=$([[ -z "$@" ]] && wofi -p "Search paru:" -dmenu || echo "$@")
SELECTED=$(paru -Ss "$SEARCH" | grep "^.*/.* \[" | wofi -dmenu -i -p "PKG:" | awk '{print $1;}')

if [[ ! -z $SELECTED ]]; then 
    $TERMINAL --class update-system paru -S $SELECTED; pause
fi


