#!/usr/bin/env sh

PROMPT="Action:"
PIDS="$(pidof wofi)"

if [ -n "$PIDS" ]; then
    kill -9 "$(pidof wofi)"
    exit
fi 
entries="󰌾\tLock\n\tLogout\n⏾\tSuspend\n󰑓\tReboot\n⏻\tShutdown"

selected=$(echo $entries | wofi --show dmenu -no-show-icons -i -p "$PROMPT" | awk '{print tolower($2)}')

case $selected in
  lock)
	  lock-system;;
  logout)
    hyprctl dispatch exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
