#!/usr/bin/env sh

PROMPT="Action: "
PIDS="$(run-launcher --pid)"

if [ -n "$PIDS" ]; then
    kill -9 $PIDS
    exit
fi 
entries="󰌾 Lock\n Logout\n⏾ Suspend\n󰑓 Reboot\n⏻ Shutdown"

selected=$(echo $entries | run-launcher "$PROMPT" | awk '{print tolower($2)}')

apply_lock() {
    case $XDG_CURRENT_DESKTOP in
        Hyprland)
            lock-system;;
        KDE)
            loginctl lock-session;;
        COSMIC)
            loginctl lock-session;;
        *)
            notify-send "Not Supported";;
    esac
            
}

apply_logout() {
    case $XDG_CURRENT_DESKTOP in
        Hyprland)
            lock-system;;
        KDE)
            qdbus6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logout;;
        COSMIC)
            cosmic-session-logout;;
        *)
            notify-send "Not Supported";;
    esac
}

case $selected in
  lock)
      apply_lock;;
  logout)
      apply_logout;;
  suspend)
      exec systemctl suspend;;
  reboot)
      exec systemctl reboot;;
  shutdown)
      exec systemctl poweroff -i;;
esac
