#!/usr/bin/env bash

PROMPT="Action:"
PIDS=$(pidof wofi)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

entries="󰌾\tLock\n\tLogout\n⏾\tSuspend\n󰑓\tReboot\n⏻\tShutdown"

selected=$(echo -e $entries | wofi -dmenu -no-show-icons -i -p "$PROMPT" | awk '{print tolower($2)}')

echo $selected

case $selected in
  lock)
	  lock-system;;
  logout)
    hyprctl dispatch exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
