#!/bin/bash

BASE_GPU_PATH="/sys/class/hwmon/hwmon5"
GPU_PCT=$(cat "$BASE_GPU_PATH/device/gpu_busy_percent")

if [[ "$1" == "full" ]]; then
    GPU_CLK_RAW=$(cat "$BASE_GPU_PATH/freq1_input")
    GPU_CLK_MHZ=$(expr $GPU_CLK_RAW / 1000000)
    echo "<big>󰡁</big> $(bc <<< "scale=2;$GPU_CLK_MHZ/1000" | sed 's/^\./0./')Ghz <span color=\"darkgray\">|  $GPU_PCT%</span>"
    exit
fi

echo "<big>󰡁</big><span color=\"#DCD7BA\">  $GPU_PCT%</span>"
