#!/usr/bin/env bash

: '
while true; do
    sleep 5
    echo "Checking for connected monitors"
    CURRENT_DISPLAY_COUNT=$(xrandr -q | grep " connected" | wc -l)

    [[ -z $OLD_DISPLAY_COUNT || $CURRENT_DISPLAY_COUNT -lt $OLD_DISPLAY_COUNT ]] \
        && OLD_DISPLAY_COUNT=$CURRENT_DISPLAY_COUNT \
        && continue 

    if [[ $CURRENT_DISPLAY_COUNT -gt $OLD_DISPLAY_COUNT ]]; then
        [[ -z $(which steam-native) ]] && STEAM_BIN="steam" || STEAM_BIN="steam-native" 

        "$STEAM_BIN" -shutdown &>/dev/null
        echo "Restarting steam"

        while [[ $(pgrep -x steam) ]]; do
            echo "Waiting for steam to shutdown"
            sleep 1
        done
        xwayland-config
        nohup "$STEAM_BIN" &>/dev/null &
        sleep 30
        pkill -9 wineboot.exe
    fi

    OLD_DISPLAY_COUNT=$CURRENT_DISPLAY_COUNT
done
'

export DISPLAY=$([[ $(ps ax | grep xwayland-display) =~ xwayland\-display\ (\:[0-9]+)\  ]] && echo "${BASH_REMATCH[1]}" || echo ":1")
export XAUTHORITY=$([[ $(ps ax | grep xwayland-display) =~ xwayland\-xauthority\ (.+)\ \- ]] && echo "${BASH_REMATCH[1]}" || echo "")
echo "$XAUTHORITY" > "/home/fpetros/hello"

CURRENT_DISPLAY_COUNT=$(xrandr -q | grep " connected" | wc -l)

if [[ $CURRENT_DISPLAY_COUNT -gt 1 ]]; then
    [[ -z $(which steam-native) ]] && STEAM_BIN="steam" || STEAM_BIN="steam-native" 

    "$STEAM_BIN" -shutdown &>/dev/null
    echo "Restarting steam"

    while [[ $(pgrep -x steam) ]]; do
        echo "Waiting for steam to shutdown"
        sleep 1
    done
    xwayland-config
    nohup "$STEAM_BIN" &>/dev/null &
    disown "%1"
    sleep 30
    pkill -9 wineboot.exe
fi
