#!/usr/bin/env sh

SCRIPTS_DIR=$([ -z "$hypr"] && echo "$HOME/.config/hypr/scripts" || echo "$hypr/scripts")

SELECTED="$(command find $SCRIPTS_DIR | \
	prune-dirs | \
	map basename | \
    grep -v "^\." | \
    cut -d'.' -f1 | \
	wofi --show dmenu -i -p "Pick a Script:")"

if [ -n $SELECTED ]; then
	ACTION=$(echo "Run\nEdit\nMake Executable\nCreate Link" | wofi --show dmenu -p "Choose an Action:")

	SCRIPT_REAL_PATH=$(find "$SCRIPTS_DIR" -wholename "*/$SELECTED*")

    case "$ACTION" in
        Run) exec "$SCRIPT_REAL_PATH";;
        Edit) $TERMINAL --class "script-editor" launch-editor "$SCRIPT_REAL_PATH";;
        Make\ Executable) exec chmod +x "$SCRIPT_REAL_PATH";;
        Create\ Link) $TERMINAL --class update-system doas ln -fs "$SCRIPT_REAL_PATH" "/usr/bin/$SELECTED";;
        *) exit
    esac	
fi

