#!/bin/bash

trap "killall -q kdeconnectd; killall -q kdeconnect-indicator; exit" SIGINT EXIT ERR

kdeconnect-indicator &

while true; do
    killall -q kdeconnectd ||
    kdeconnectd &
    wait %2
done

