#!/usr/bin/env dash

CONFIG="$hypr/config/waybar/config-hypr.jsonc"
STYLE="$hypr/config/waybar/style.css"
MODULES="$hypr/config/waybar/modules.jsonc"

CONFIG_FILES="$CONFIG $STYLE $MODULES"

trap "killall waybar; exit" EXIT SIGINT

while true; do
    waybar --log-level error --config ${CONFIG} --style ${STYLE} &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
