#!/bin/bash

trap "killall -q swaync; exit" SIGINT

CONFIG="$hypr/config/swaync/config.json"
STYLE="$hypr/config/swaync/style.css"

CONFIG_FILES="$CONFIG $STYLE"

swaync &

while true; do
	inotifywait -e create,modify $CONFIG_FILES
	swaync-client -R
	swaync-client -rs
done
