#!/usr/bin/env dash

for HIDRAW_ID in $(ls /dev | grep hidraw); do
    DEVICE=$(cat /sys/class/hidraw/${HIDRAW_ID}/device/uevent | grep HID_NAME | cut -d '=' -f2-)
    [ "$(echo "$DEVICE" | grep -E "^Vaydeer")" ] &&\
        cat /dev/${HIDRAW_ID} &> /dev/null &
done  

wait
