#!/usr/bin/env dash

ARG_STRING=""

while read arg
do
	if [ -n $arg ]; then
		#ESCAPED_ARG=$(echo "${arg/\"/\\\"}")
		#ESCAPED_ARG=$(echo "${ESCAPED_ARG/\ /\\\ }")
		ARG_STRING="$ARG_STRING$(echo "\"$arg\" ")"
	fi
done < /dev/stdin

echo "${ARG_STRING%%*( )}"

