#!/usr/bin/env sh

MAP_CMD="$1"
CMD="$2"
ARG_STRING=""

while read arg
do
	if ! [ "$MAP_CMD" = "$arg" ]; then
		ARG_STRING="$ARG_STRING$(echo $("$MAP_CMD" "$arg")\ )"
	fi
done < /dev/stdin

#echo "${ARG_STRING%%*( )}"

[ -z "$CMD" ] &&\
    echo $ARG_STRING ||\
    "$CMD" $ARG_STRING

