#!/usr/bin/env dash

# Wait for XWayland to Start
XWAYLAND_PID=$(pidof Xwayland)

while [ -z "$XWAYLAND_PID" ]; do
	echo "XWayland not found, sleeping for 5 seconds"
	sleep 5
	XWAYLAND_PID=$(pidof Xwayland)
done

# Allow xhost for all local users
xhost + local:

MAIN_MONITOR_RESOLUTION="$(xrandr | grep 'DP-1' | awk '{ print $3 }' | cut -d'+' -f1)" || MAIN_MONITOR_RESOLUTION="1920x1080"

# Set XWayland Primary Monitor
xrandr --output "$(xrandr | awk '/'"$MAIN_MONITOR_RESOLUTION"'/ {print $1}' | head -n 1)" --primary
